package com.codercamp.quran.constant

class Name {
    fun data(): ArrayList<String> {
        val data = ArrayList<String>()
        data.add("The Opening")
        data.add("The Cow")
        data.add("The Family of Imran")
        data.add("The Women")
        data.add("The Table")
        data.add("The Cattle")
        data.add("The Heights")
        data.add("The Spoils of War")
        data.add("The Repentance")
        data.add("Yunus")
        data.add("Hud")
        data.add("Yusuf")
        data.add("The Thunder")
        data.add("Ibrahim")
        data.add("The Rocky Tract")
        data.add("The Bees")
        data.add("The Night Journey")
        data.add("The Cave")
        data.add("Maryam")
        data.add("Ta-Ha")
        data.add("The Prophets")
        data.add("The Pilgrimage")
        data.add("The Believers")
        data.add("The Light")
        data.add("The Criterion")
        data.add("The Poets")
        data.add("The Ants")
        data.add("The Stories")
        data.add("The Spider")
        data.add("The Romans")
        data.add("Luqman")
        data.add("The Prostration")
        data.add("The Combined Forces")
        data.add("The Sabeans")
        data.add("The Originator")
        data.add("Ya-Sin")
        data.add("Those Ranges in Ranks")
        data.add("Sad")
        data.add("The Groups")
        data.add("The Forgiver")
        data.add("Distinguished")
        data.add("The Consultation")
        data.add("The Gold")
        data.add("The Smoke")
        data.add("The Kneeling")
        data.add("The Valley")
        data.add("Muhammad")
        data.add("The Victory")
        data.add("The Dwellings")
        data.add("Qaf")
        data.add("The Scatterers")
        data.add("The Mount")
        data.add("The Star")
        data.add("The Moon")
        data.add("The Most Gracious")
        data.add("The Event")
        data.add("The Iron")
        data.add("The Reasoning")
        data.add("The Gathering")
        data.add("The Tested")
        data.add("The Row")
        data.add("Friday")
        data.add("The Hypocrites")
        data.add("The Loss & Gain")
        data.add("The Divorce")
        data.add("The Prohibition")
        data.add("The Kingdom")
        data.add("The Pen")
        data.add("The Inevitable")
        data.add("The Elevated Passages")
        data.add("Nuh")
        data.add("The Jinn")
        data.add("The Wrapped")
        data.add("The Cloaked")
        data.add("The Resurrection")
        data.add("The Human")
        data.add("Those Sent Forth")
        data.add("The Great News")
        data.add("Those Who Pull Out")
        data.add("He Frowned")
        data.add("The Overthrowing")
        data.add("The Cleaving")
        data.add("Those Who Deal in Fraud")
        data.add("The Splitting Asunder")
        data.add("The Stars")
        data.add("The Nightcomer")
        data.add("The Most High")
        data.add("The Overwhelming")
        data.add("The Dawn")
        data.add("The City")
        data.add("The Sun")
        data.add("The Night")
        data.add("The Forenoon")
        data.add("The Opening Forth")
        data.add("The Fig")
        data.add("The Clot")
        data.add("The Night of Decree")
        data.add("The Proof")
        data.add("The Earthquake")
        data.add("The Runners")
        data.add("The Striking Hour")
        data.add("The Piling Up")
        data.add("The Time")
        data.add("The Slanderer")
        data.add("The Elephant")
        data.add("Quraish")
        data.add("The Assistance")
        data.add("The River of Abundance")
        data.add("The Disbelievers")
        data.add("The Help")
        data.add("The Palm Fiber")
        data.add("The Sincerity")
        data.add("The Daybreak")
        data.add("Mankind")
        return data
    }
}